media_analysis_task:
  description: >
    Analyze news articles from {path_to_daily_media} dated {media_date}.
    For each article, extract useful information and identify connections 
    between political candidates and entities supporting this candidate 
    with respect to the stock market given the stocks performance one day
    after the news was published.

    Only report what makes sense, do not force any correlations.

    Stock reports per ticker are available at {path_to_daily_reports_stocks} 
    Stock reports per sector are available at {path_to_daily_reports_sectors}.

  expected_output: >
    Example Output:
    - Primary Candidate: {reference_candidate_party_two}
    - Entity: {reference_associated_entity_party_two}
    - Date: {media_date}
    - News Article: news article title
    - Economy Impact: How do you think this opinion from candidate or entity will 
    impact the economy in the short and long term?
    - Sentiment: Positive, Negative, Neutral
    - Confidence Level: 1 to 5

stock_impact_analysis_task:
  description: >
    Analyze the stock report at {path_to_daily_reports_stocks} for {report_date}, 
    identifying the largest positive and negative movers compared to the previous 
    day, with insights based on all relevant news from {path_to_daily_media} 
    published on {media_date}.
    
    Reason if the stock movement has some influence due to the either candidate 
    ({reference_candidate_party_one} or {reference_candidate_party_two})
    or the entities supporting this candidate 
    (ex: {reference_associated_entity_party_one} or {reference_associated_entity_party_two}).

    Do NOT force any correlations between the stock report, news, and the candidate.
    Report only what makes sense.

  expected_output: >
    - List of Stocks Affected (if any):
      - Candidate Name (If no candidate is directly correlated skip this item, move to the next one.)
      - Stock Ticker
      - Stock Variation
      - Confidence Level (1 to 5, with 5 indicating the highest confidence)
      - Impact Strength (1 to 5, with 5 indicating the highest impact)
      - Sentiment (Positive, Negative, Neutral)
      - Why do you think this stock is affected?
    
    All fields above are required. Do not come up with conclusions that are not in 
    any of the files you analyzed ({path_to_daily_media} and {path_to_daily_reports_stocks}). 
    You're completely forbidden to create conclusions that are not in the files.

    Formatted as markdown without '```'

sector_impact_analysis_task:
  description: >
    Analyze the sector report at {path_to_daily_reports_sectors} for {report_date}, 
    identifying the largest positive and negative movers compared to the previous 
    day, with insights based on all relevant news from {path_to_daily_media} 
    published on {media_date}.

    Reason if the sector movement has some influence due to the either candidate 
    ({reference_candidate_party_one} or {reference_candidate_party_two})
    or the entities supporting this candidate 
    (ex: {reference_associated_entity_party_one} or {reference_associated_entity_party_two}).

    Do NOT force any correlations between the sector report, news, and the candidate.
    Report only what makes sense.

  expected_output: >
    - List of Sectors Affected (if any):
      - Candidate Name (If no candidate is directly correlated skip this item, move to the next one.)
      - Sector Name
      - Sector Variation
      - Confidence Level (1 to 5, with 5 indicating the highest confidence)
      - Impact Strength (1 to 5, with 5 indicating the highest impact)
      - Sentiment (Positive, Negative, Neutral)
      - Why do you think this sector is affected?
    
    All fields above are required. Do not come up with conclusions that are not in 
    any of the files you analyzed ({path_to_daily_media} and {path_to_daily_reports_sectors}). 
    You're completely forbidden to create conclusions that are not in the files.
    
    Formatted as markdown without '```'