_target_: src.models.forecast.lstm_module.LSTMForecastModule

# training strategy
loss: "mse_loss"

outputs:
  train: ["loss", "preds", "targets"]
  val: ["loss", "preds", "targets"]
  test: ["loss", "preds", "targets"]

# LSTM parameters
input_size: 1           # Number of features in the input data
hidden_size: 64        # Number of features in the hidden state
num_layers: 2           # Number of recurrent layers
dropout: 0.2            # Dropout probability for LSTM layers

optimizer:
  _target_: torch.optim.Adam
  _partial_: true
  lr: 0.0001

scheduler: null
