_target_: src.models.forecast.lstm_module.LSTMForecastModule

# training strategy
loss: "mse_loss"

# outputs
outputs:
  train: ["preds", "targets"]
  val: ["preds", "targets"]
  test: ["preds", "targets"]

# evaluation
save_recs: False

optimizer:
  _target_: torch.optim.Adam
  _partial_: true
  lr: 0.0001

scheduler: null
